# Generated by Django 5.2.5 on 2025-08-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedisMetric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('raw_info', models.JSONField(default=dict)),
                ('memory_used', models.FloatField(null=True)),
                ('ops_per_sec', models.IntegerField(null=True)),
                ('hit_rate', models.FloatField(null=True)),
                ('rejected_connections', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
